### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by TomislavSmvc** [Azure-Samples/ms-identity-java-webapi#20]
I cloned both projects on my PC and followed the instruction to the best of my abilities, but when i run the projects trough my IDE (i use Eclipse) i get this error:

1. I get the initial page with the "Login" button
2. Pressing it prompts the external Microsoft login and upon succesfull log-on (and permission requestst) it redirects me to the page with the "Call OBO api" button.
3. Pressing that button redirects me to the error page, and the the console for the "msal-web-sample" on Eclipse prints these exceptions:

2021-03-29 20:27:19.240 ERROR 11032 --- [nPool-worker-11] c.m.a.m.ConfidentialClientApplication    : [Correlation ID: 274b3c76-e518-4d33-8b8a-8dc99002f45d] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.

```
com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.
Trace ID: 1a42e143-d9e7-4510-aac8-0018e893b200
Correlation ID: 274b3c76-e518-4d33-8b8a-8dc99002f45d
Timestamp: 2021-03-29 18:27:17Z
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:37) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:90) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:38) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:117) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:53) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59) [msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17) [msal4j-1.6.1.jar:1.6.1]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [na:1.8.0_191]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [na:1.8.0_191]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [na:1.8.0_191]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [na:1.8.0_191]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [na:1.8.0_191]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [na:1.8.0_191]

2021-03-29 20:27:19.241 ERROR 11032 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.
Trace ID: 1a42e143-d9e7-4510-aac8-0018e893b200
Correlation ID: 274b3c76-e518-4d33-8b8a-8dc99002f45d
Timestamp: 2021-03-29 18:27:17Z] with root cause

com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.
Trace ID: 1a42e143-d9e7-4510-aac8-0018e893b200
Correlation ID: 274b3c76-e518-4d33-8b8a-8dc99002f45d
Timestamp: 2021-03-29 18:27:17Z
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:37) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:90) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:38) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:117) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:53) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17) ~[msal4j-1.6.1.jar:1.6.1]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:1.8.0_191]


```

What could i have done wrong to get this message?
The exact line of code that throws the error is:
msal-web-sample -> AuthHelper.java -> Line 71

I noticed that in:
msal-web-sample -> AuthFilter.java -> Line 214 and Line 216
you are adding "openid offline_access profile" to WEBAPI_DEFAULT_SCOPE, but nowhere in the instruction is it mentioned that those are needed to be added to the App Registrations when setting up the Azure Apps. Could that be a problem?

**Comment by TomislavSmvc** [comment]
Also, when i create a personal test account and i try to login, on the consent form i get no mention of the Back-end WenAPI App, only the permissions declared on the FFrontend WebApp App

**Comment by prof18** [comment]
I have the same problem. It happens because the jwtIssuer does not contain the tenant id specified in the conf file. Am I missing something?

**Comment by TomislavSmvc** [comment]
I also noticed that when i try to sing in with a test user, then on the consent form, nowhere does it mention the java-webapi app. Is this normal?

**Comment by TomislavSmvc** [comment]
And as @prof18 mentioned, then TenantID shown on the HomePage of the Webapp differs from the tennantID shown in the Azure App registration.
If put this mistery tenantID into security.oauth2.accepted.tenants in the application.properties of the Java wepAPI, then pressing the "Call OBO api" actually gets me into the Java WebAPI, but once it tries to get the acces token in order to call Graph API, it gets this exception:

```
com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.
Trace ID: d0915a4d-de86-4d8f-bc88-7f85db873d00
Correlation ID: bb593506-f7c2-43de-8544-65b1f1c41be0
Timestamp: 2021-04-12 17:57:49Z
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:37) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:90) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:38) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:117) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17) ~[msal4j-1.6.1.jar:1.6.1]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:1.8.0_191]

```

**Comment by sangonzal** [comment]
@TomislavSmvc The tenantId in the home page is the home tenant of the user who signed in, which might be different from the tenant in which your application is registered in. 

If you go to the portal and grant admin consent for the tenant, does that fix your issue? 

I tried to run the sample and also ran into some issues, so I submitted a pull request to clean things up. I hope to get this merged in this week, but in the meantime if you want you can try using branch "update-sample"

**Comment by TomislavSmvc** [comment]
@sangonzal I will try the new branch and let you know, thank you.

btw. for both App registrations under "API permissions" i clicked the "Grant admin consent for <tenant name>"  for all permissions.

**Comment by TomislavSmvc** [comment]
@sangonzal This time it works, but only if i put the TennantID of my User in security.oauth2.accepted.tenants in the application.properties of the Java-webAPI.
Whatt am i supposed to put there in order to work with any user?

btw. in the application.properties of the Java-webapp, you forgot to replace aad.apiDefaultScope

**Comment by prof18** [comment]
I still getting the 

```
com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope
```

And I can't understand why. I've followed the readme and I don't understand why does not work.
